### ISSUE TITLE
`GaussIndependent()` different output

### ISSUE THREAD

**Issue by lovestat** [statisticsnorway/SSBtools#28]
Dear Oyvind,

Please try the below codes
```
y.url <- "https://raw.githubusercontent.com/lovestat/speedglm-test/main/y_vanderbilt.rds"
x.url <- "https://raw.githubusercontent.com/lovestat/speedglm-test/main/x.dgR.rds"
download.file(y.url,"y.rds", method="curl")
download.file(x.url,"x.rds", method="curl")
y <- readRDS("y.rds")
x <- readRDS("x.rds")
class(y)
class(x)

xNums <- 300
x_dgR <- x[, 1:xNums ]

get_nld_col <- function(x){
  x$pivot[1:(x$rank)]
}

x_dgR_GI <- SSBtools::GaussIndependent(x_dgR)
sum(which(x_dgR_GI$columns))
#> 44740
x_dgR_qr <- base::qr(as.matrix(x_dgR))
sum(get_nld_col(x_dgR_qr))
#> 44734
```

**Comment by olangsrud** [comment]
In this case both methods agree that the rank is 297, but I see that `qr` picks up column number 134 and `GaussIndependent` does not. The results differ and in general the rank may also differ.

The description of `GaussIndependent` says that “The function is written primarily for large sparse matrices”. But in fact, the function is primarily written for large sparse matrices with integers. An even more correctly it is primarily written for dummy matrices (0s and 1s in input matrix). This is the main use of the function. 

The main algorithm is based on integers and exact calculations. When integers cannot be used (because of input or overflow), the algorithm switches.  If you include `printInc = FALSE `as a parameter you will see that `.....` change to `-----`. In our applications, `-----` rarely happens.

When switching to numeric algorithm a kind of tolerance for linear dependency is included. This tolerance is designed having in mind that the input matrix is a dummy matrix.

Thanks for the example. I will change the documentation and warn that the function is written primarily for integer/dummy matrices. 

```
SSBtools::GaussRank(x_dgR, printInc = TRUE)        # numeric calculations
SSBtools::GaussRank((x_dgR>0)*1, printInc = TRUE)  # integer calculations 
```

**Comment by olangsrud** [comment]
Closes the issue since the documentation has been changed as mentioned above.
